platform :ios, '9.3'
use_frameworks!

target 'MyLib_Example' do
  pod 'MyLib', :path => '../'

  target 'MyLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.4'
    pod 'Nimble', '~> 7.3.4'
  end
end
