# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

env:
  matrix:
    - DEST='platform=iOS Simulator,name=iPhone 7,OS=12.1'
    - DEST='platform=iOS Simulator,name=iPhone X,OS=12.1'

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
#  - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MyLib.xcworkspace -scheme MyLib-Example -destination $DEST ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
